sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - DEPLOY_DOCS=true

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  - travis_retry composer install --no-interaction
  - composer info -i

after_success:
  - chmod +x ./docs/deploy.sh
  - ./docs/deploy.sh

notifications:
  email: true
