sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 7
      env:
        - DEPLOY_DOCS=true

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update

install:
  - travis_retry composer install --no-interaction
  - composer info -i
  - echo ${TRAVIS_BUILD_DIR}
  - ls
  - ls docs

after_success:
  - if [[ $DEPLOY_DOCS == 'true' ]]; then ./docs/deploy.sh || return 0 ; fi

notifications:
  email: true
