sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 7
      env:
        - DEPLOY_DOCS=true

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update

install:
  - travis_retry composer install --no-interaction
  - composer info -i
  - echo ${TRAVIS_BUILD_DIR}
  - ls
  - ls docs

after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) &&
      [ "$TRAVIS_PULL_REQUEST" == "false" ] &&
      [ "$DEPLOY_DOCS" == "true" ]; then
    echo "This will deploy!"
  else
    echo "This will not deploy!"
  fi

notifications:
  email: true
